//
//  BTViewControllerSetting.m
//  BT
//
//  Created by apple on 2018/1/15.
//  Copyright © 2018年 apple. All rights reserved.
//

#import "BTViewControllerSetting.h"

@implementation BTViewControllerSetting

NSDictionary *BTViewControllerMap() {
    return @{@"home":@"HomeViewController",
             @"quotes":@"QuotesViewController",
             @"infomation":@"BTNewSheQuMainViewController",
             @"market":@"PlatformViewController",
             @"user":@"UserCenterViewController",
             @"second":@"SecondViewController",
             @"logion":@"LoginAndRegisterViewController",
             @"signIn":@"SignInAndTanLiViewController",
             @"personSetting":@"PersonSettingViewController",
             @"actionSheet":@"HYActionSheetViewController",
             @"FeedBack":@"FeedBackViewController",
             @"SystemSetting":@"SystemSettingViewController",
             @"myoption":@"MyOptionViewController",
             @"editoption":@"EditOptionViewController",
             @"MyNewCollectionVC":@"MyNewCollectionViewController",
             @"MessageCenter":@"MessageMainListViewController",
             @"quotesdetail":@"QuotesDetailViewController",
             @"webView":@"H5ViewController",
             @"historySearch":@"HistorySearchViewController",
             @"pinglunxiangqing":@"CommentDetailViewController",
             @"wenzhangxiangqing":@"H5InfomationDetailViewController",
             @"xianhuoxiangqing":@"XianHuoDetailViewController",
             @"qihuoxiangqing":@"QiHuoDetailViewController",
             @"LncomeStatisticsMain":@"LncomeStatisticsMainViewController",
             @"AddRecord":@"AddRecordViewController",
             @"ChooseJYD":@"ChooseJYDViewController",
             @"ProfitLossStatVC":@"QuoteProfitLossStatVC",
             @"ProfitCurveVC":@"BTProfitLossCurveVC",
             @"DiscoveryMain":@"DiscoveryViewController",
             @"xianhuoVC":@"XianHuoMainViewController",
             @"qihuoVC":@"QiHuoMainViewController",
             @"CurrencyConceptsVC":@"CurrencyConceptsVC",
             @"NewCurrencyOnSaleVC":@"NewCurrencyOnSaleViewController",
             @"PayConceptVC":@"PayConceptViewController",
             @"MyTanLiVC":@"MyTanLiViewController",
             @"InviteFriendVC":@"InviteFriendVC",
             @"TPInviteFriendVC":@"InviteFriendViewController",
             @"MyTanLiDetailVC":@"BTMyTanliDetailVC",
             @"TopicVC":@"TopicViewController",
             @"CommentsDetailVC":@"CommentsDetailViewController",
             @"ZanAndReplayListVC":@"ZanAndReplayListViewController",
             @"manageGroup":@"BTManageGroupVC",
             @"priceWarning":@"BTPriceWarningVC",
             @"BTNewAddRecord":@"BTNewAddRecordViewController",
             @"BTChooseWallet":@"BTChooseWalletViewController",
             @"BTExchangeAuthorization":@"BTExchangeAuthorizationViewController",
             @"BTExchangeDetailLncome":@"BTExchangeDetailLncomeViewController",
             @"BTIndexDetail":@"BTIndexDetailViewController",
             @"OptionSearch":@"OptionSearchViewController",
             @"Register":@"RegisterViewController",
             @"SettingOrChange":@"SettingOrChangeViewController",
             @"ForgetPassword":@"ForgetPasswordViewController",
             @"BTHomeGongGaoDetail":@"BTHomeGongGaoDetailViewController",
             @"BTZFFBDetail":@"BTZFFBDetailViewController",
             @"BTZFFBDetailDetail":@"BTZFFBDetailDetailViewController",
             @"ForgetPassword":@"ForgetPasswordViewController",
             @"BTJingCaiMain":@"BTJingCaiMainViewController",
             @"BTMyJingCai":@"BTMyJingCaiViewController",
             @"BTJingCaiDetail":@"BTJingCaiDetailViewController",
             @"FutureList":@"QiHuoListViewController",
             @"QiHuoDetailVC":@"QiHuoDetailVC",
             @"BTPingjiViewController":@"BTPingjiViewController",
             @"JSH5":@"JSH5ViewController",
             @"BTNewCommentsAlert":@"BTNewCommentsAlertViewController",
             @"BTNewDianZanAndReplayDetail":@"BTNewDianZanAndReplayDetailViewController",
             @"BTNewMyTanLiMain":@"BTNewMyTanLiMainViewController",
             @"BTNewMyTanLiChild":@"BTNewMyTanLiChildViewController",
             @"BTICOListViewController":@"BTICOListViewController",
             @"BTICODetailViewController":@"BTICODetailViewController",
             @"BTCoinAddressAnalyseVC":@"BTCoinAddressAnalyseVC",
             @"BTCandyViewController":@"BTCandyViewController",
             @"BTNewCommentsAlert":@"BTNewCommentsAlertViewController",
             @"BTExchangeContainerVC":@"BTExchangeContainerVC",
             @"BTPostComposeViewController":@"BTPostComposeViewController",
             @"BTPostDetailViewController":@"BTPostDetailViewController",
             @"YCPhotoBrowserController":@"YCPhotoBrowserController",
             @"BTTransmitPostVCViewController":@"BTTransmitPostVCViewController",
             @"BTMyPostViewController":@"BTMyPostViewController",
             @"BTContactUsViewController":@"BTContactUsViewController",
             @"BTSelectPersonVC":@"BTSelectPersonVC",
             @"BTPersonViewController":@"BTPersonViewController",
             @"BTFocusViewController":@"BTFocusViewController",
             @"BTFansViewController":@"BTFansViewController",
             @"BTFabuViewController":@"BTFabuViewController",
             @"BTHelpCenterViewController":@"BTHelpCenterViewController",
             @"BTTanliDetailListVC":@"BTTanliDetailListVC",
             @"BTTPRewardVC":@"BTTPRewardVC",
             @"BTUserPraiseVC":@"BTUserPraiseVC",
             @"BTColleageVC":@"BTColleageVC",
             @"BTColleageDetailVC":@"BTColleageDetailVC"
             
             };
}

@end
